### ISSUE TITLE
[BUG] Mobile menu on iphone5 & phone landscape shows top level nav when selected second level name

### ISSUE THREAD

**Issue by TimMansell** [unimelb/pattern-lib#1034]
## Expected behaviour

When second level nav is open the first level nav should be completely hidden.

![Screen Shot 2019-04-24 at 12 47 30 pm](https://user-images.githubusercontent.com/1926461/56628968-2fcf9300-668f-11e9-80f4-22e85ab95873.png)

## Current behaviour

![Screen Shot 2019-04-24 at 12 43 27 pm](https://user-images.githubusercontent.com/1926461/56628870-d8c9be00-668e-11e9-80bf-39ac96adbef0.png)

**Comment by gepifanio** [comment]
Fixed already
