### ISSUE TITLE
Heading size increases

### ISSUE THREAD

**Issue by woowoowoo** [unimelb/pattern-lib#1068]
Prior to the latest release, font size of headings were smaller.

For example.
Before: https://maps.unimelb.edu.au/parkville/building/199?dev=v4.3.0
After: https://maps.unimelb.edu.au/parkville/building/199

It's something to do with selectors like **.content-block h2** overriding the **heading-card** classes.

Before:
![before](https://user-images.githubusercontent.com/848310/57597148-8135b880-7591-11e9-8072-b75c555f099f.png)
After:
![after](https://user-images.githubusercontent.com/848310/57597147-809d2200-7591-11e9-99e3-3e41ded83f32.png)

**Comment by jaredh-um** [comment]
Hi @woowoowoo, there is a new helper class available to size headings appropriately while still retaining the appropriate semantic tag (ie; H2). Please check [Typography > Heading](https://pattern-lib-unimelb.netlify.com/?selectedKind=Typography&selectedStory=Heading%20Component&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel) component in the Pattern Library.

However, you are correct in that the `.content-block h1` selector (and so on) is overriding the classes applied to the headings, so this solution won't help for now. @TimMansell?

If you require specific styling for H2s etc. for maps.unimelb (ie; not using Noto Serif) I would suggest requesting a custom class or override from front-end so they remain constant when other components get updated (perhaps under the `building` class or something unique to maps.unimelb)

**Comment by woowoowoo** [comment]
For the problem on maps.unimelb I've just added some hacky overrides to the local style sheet. At least now the pages are back to normal. When you get around to addressing the problem, I can help reproduce the problem for you to test against.

**Comment by jaredh-um** [comment]
This has been partially [addressed](https://app.zenhub.com/workspaces/global-design-system-issues-tracker-603c265651b123001c916450/issues/unimelb/pattern-lib/1254) but the core issue is that there are generic heading styles that have a very broad cascade and are thus difficult to override on a single class/instance basis.

Unfortunately this would require a significant refactor to the way Gen 2 is constructed (scoping heading styles to specific parts of the page, refactoring components to use new utility styles etc.) This is unlikely to occur while we are in the process of winding down Gen 2 with a view to improving on these issues in Gen 4, so I will close this issue for now.
