### ISSUE TITLE
[Bug] Select--blue has white background on windows computers

### ISSUE THREAD

**Issue by kebfrf** [unimelb/pattern-lib#1078]
Bug reported on Windows computer (unable to reproduce on Mac without emulator). Affecting Study. 

## What
Wherever the dropdown component 
Tested IE11 Windows emulator: 
https://study.unimelb.edu.au/find/courses/graduate/master-of-agricultural-sciences/entry-requirements/ 
![Screen Shot 2019-05-14 at 4.16.03 pm.png](https://images.zenhubusercontent.com/5ab48f164b5806bc2bcc1060/7ee23a77-e976-4996-8e32-7309d5eaed14)

### User report:
There is a drop down list at https://study.unimelb.edu.au/find/courses/graduate/master-of-information-systems/entry-requirements/ It looks like there's only one option, but it's actually white text on a white background, so the text is visible when you scroll over it. See attached pic. Have tested it on all browsers on a Windows laptop and it is occurring on all three:

The issue is happening in Chrome version 74.0.3729.131 – two different computers
Internet Explorer – can't work out how to tell what version it is
Microsoft Edge – can't work out how to tell what version it is

Another staff member also tested it on Windows with the same result. The error doesn't seem to occur on Mac OS desktop computer.

## Steps to reproduce

1. As on mac computer, when to browserling.com and entered https://study.unimelb.edu.au/find/courses/graduate/master-of-agricultural-sciences/entry-requirements/, selecting IE 11 and windows
2. tested select menu 
3. Repeated on https://study.unimelb.edu.au/find/courses/graduate/master-of-public-health/what-will-i-study/

### Affected browsers

- [x] Chrome
- [ ] Firefox
- [x] Edge
- [x] IE 11
- [ ] Safari 8+
- [ ] iOS 8.4+
- [ ] Android 4.4+
Note: WINDOWS ONLY - not able to reproduce on mac. Definitely not happening on firefox on windows. 

## Possible solution
I think something happened in this commit: https://github.com/unimelb/pattern-lib/commit/db589eeba4b184c47a3efa38d2d26ef159726543#diff-2d3d8f79efdbd0be1a162a17fb5f756a 

## Additional
- colour contrast of this blue isn't accessible - @jaredh-um proposed change, not sure if this is documented anywhere

**Comment by jaredh-um** [comment]
Colour replacement for blue is in this [ticket](https://github.com/unimelb/ffam-prototype/issues/369) in FFAM (UoM Navy).

**Comment by jaredh-um** [comment]
If this component requires rebuilding/restyling, I have proposed the colour change above and a restyle/restructure [here](https://github.com/unimelb/ffam-prototype/issues/435). The existing dropdown is a Vue component where my proposed change is CSS only, so it is still accessible.

**Comment by jaredh-um** [comment]
@gepifanio 

Found the bug. There is an invalid `color` property set on the `.styled-select select option` selector (try saying that ten times fast!)

Fix: change `color` value to `rgb(0,0,0)`

![Screen Shot 2019-05-15 at 2 38 54 pm](https://user-images.githubusercontent.com/34703139/57748966-81fc5500-771f-11e9-9163-8b530a2312af.png)

**Comment by gepifanio** [comment]
PR: https://github.com/unimelb/pattern-lib/pull/1122
