### ISSUE TITLE
Inverted button down state renders text invisible

### ISSUE THREAD

**Issue by jaredh-um** [unimelb/pattern-lib#1082]
## Expected behaviour

Button text should remain visible while the button is being pressed.

## Current behaviour

The down state of the button turns the background white, and the text remains white rendering it invisible.

![Screen Shot 2019-05-15 at 11.50.27 am.png](https://images.zenhubusercontent.com/5acae0cd4b5806bc2bce3338/04f0f2b1-b916-4fb9-a9b9-f2bcf08f3b78)

## Steps to reproduce

1. Go to [Pattern Library](https://pattern-lib-unimelb.netlify.com/?selectedKind=Buttons&selectedStory=Inverted%20button&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel)
2. Click the demo button

**Comment by TimMansell** [comment]
@jaredh-um, I have fixed this as part of the button style updates in https://github.com/unimelb/pattern-lib/pull/1080
