### ISSUE TITLE
[Component] Mobile toggle block tweaks

### ISSUE THREAD

**Issue by woowoowoo** [unimelb/pattern-lib#1100]
## Improvement / Feature request

The mobile-toggle-block thing is a great space saver, but there are two problems:

a) On a small screen, when you've scrolled down to the bottom of a toggled area, and tap the 'close panel' button, everything just collapses upward, leaving you at a scroll position well down the page (usually looking at the footer). I'd like to see the page scroll back to the top of the toggle block.

b) I'd like to see an alternate 'light' colour scheme introduced for the toggle controls. Being in dark blue it's a very heavy element on screen, and I feel it distracts. I've implemented it on maps.unimelb buildings, eg: https://maps.unimelb.edu.au/parkville/building/101/ to hide some of the less important text information, but I've hacked up some override styles to change the foreground/background colors.

**Comment by TimMansell** [comment]
HI @jaredh-um, any suggestions?

**Comment by jaredh-um** [comment]
@TimMansell I agree with both Andrew's points; let me mock something up for a light version. Be nice to smooth out the transition with an ease as well.
