### ISSUE TITLE
Replace unhoused logo with housed logo

### ISSUE THREAD

**Issue by jaredh-um** [unimelb/pattern-lib#1134]
### Current behaviour
The current version of the logo used on the website has no background colour and is only as big as the logo itself (ie; there is no spacing around the edge). This means the background colour and outer margin needs to be set manually in CSS whenever it is used.

It also appears in Google results as transparent.

Presumably this was done by the devs to allow for future background colour changes but this is unlikely to happen (and can be done by swapping the logo file anyway).

![Unknown.png](https://images.zenhubusercontent.com/5acae0cd4b5806bc2bce3338/616b5589-26ce-4ea2-bdde-c3784bb10642)

### Proposed fix

Replace the current logo.svg with the housed version. This will involve remediation to account for the change in dimensions across:

- [ ] The homepage
- [x] L1 banner
- [x] L2 banner
- [x] L3 banners
- [ ] Most campaign banners
- [ ] Mega menu + mobile menu
- [x] Footer
 - [ ] Align logo with the text ?:

Current:
![image.png](https://images.zenhubusercontent.com/5be8f6294f44731953087568/d3e45b86-6e56-4afb-b79f-1294810b4ad8)

Expect:
![image.png](https://images.zenhubusercontent.com/5be8f6294f44731953087568/d060da7a-e5ee-49d4-9608-612c9a704e66)

- any other location the logo is used on the website.

![PRIMARY_A_Vertical_Housed_RGB.svg](https://images.zenhubusercontent.com/5acae0cd4b5806bc2bce3338/10cc884b-f3d8-490c-9ac8-e3ab2257c24f)

**Comment by TimMansell** [comment]
This has been released.
