### ISSUE TITLE
Problems with simple header page

### ISSUE THREAD

**Issue by woowoowoo** [unimelb/pattern-lib#1135]
https://maps.unimelb.edu.au/search uses the basic lower level page template.

In Chrome/Mac Version 74.0.3729.169, when I click on the logo, the active state (mouse down) causes the angle border to spectacularly reveal itself. See screen shot. Also happened on Firefox/Mac 67.0, Chrome/Win.

![Screen Shot 2019-05-31 at 9 17 34 am](https://user-images.githubusercontent.com/848310/58671368-c45f9c00-8385-11e9-9b59-5a4d2c5643ea.png)

**Comment by gepifanio** [comment]
PR: https://github.com/unimelb/pattern-lib/pull/1175

**Comment by TimMansell** [comment]
This has been fixed.
