### ISSUE TITLE
Width problem in simple header

### ISSUE THREAD

**Issue by woowoowoo** [unimelb/pattern-lib#1136]
Noted on https://maps.unimelb.edu.au/search, which uses the basic lower level header, but also noted on other pages such as: https://about.unimelb.edu.au/leadership/chancellor.

When the browser window is sufficiently wide (very wide), the Uni logo overlaps against the wave background. See screen shot.

![Screen Shot 2019-05-31 at 9 18 52 am](https://user-images.githubusercontent.com/848310/58671508-39cb6c80-8386-11e9-89c5-bf4110418b19.png)

**Comment by TimMansell** [comment]
Hi @jaredh-um, any suggestions on how the logo should be positioned?

**Comment by jaredh-um** [comment]
@TimMansell The logo itself is in the correct position (flush with the breadcrumbs and page container). However the shape inside the header should stop before it reaches the logo. Have just had a look at the markup and the shape is being positioned fairly basically using a `left` % value.

If you increase the % level it pushes the shape further away from the logo. So you could apply this at a high breakpoint and above (the example below is at 40%).

What would be better is if there was some kind of barrier on the RHS of the logo to prevent this happening but I'm not sure if this is possible with the current markup.

**Comment by gepifanio** [comment]
Solved already.
