### ISSUE TITLE
[BUG] Full width image background position crops image

### ISSUE THREAD

**Issue by dkevey** [unimelb/pattern-lib#1137]
Currently the `.full-width-image {background-position: top;}` which crops the image. This would mean editors would need to spend hours adjusting their images to suit - it is preferable to change position to center. 

https://study.unimelb.edu.au/connect-with-us/international/china

![image](https://user-images.githubusercontent.com/1305804/58675567-435dd000-8398-11e9-91df-ccc2f933e7ed.png)

Have added a temporary override as this affects Study and FFAM. 

![image](https://user-images.githubusercontent.com/1305804/58675722-f0384d00-8398-11e9-916b-071d0a1b0bba.png)

## Possible solution
Change background-position to center image. 
`.full-width-image {background-position: center;}`

**Comment by TimMansell** [comment]
Hi @jaredh-um, checking with you first before we implement this change.

**Comment by jaredh-um** [comment]
@TimMansell this is fine, Donna had discussed it with me last week.
