### ISSUE TITLE
Campaign banner 2019 - add inverted/dark version

### ISSUE THREAD

**Issue by jaredh-um** [unimelb/pattern-lib#1138]
### Currently

We have a version of the 2019 recruitment campaign banner that is working well for the creative that is being provided (with light grey backgrounds). Donna has set up a preview of these in the Matrix content container template [documentation](https://matrix-cms.unimelb.edu.au/web/mce/content-templates/campaign-banner/_recache?cct=dev).

![Screen Shot 2019-05-31 at 3.32.53 pm.png](https://images.zenhubusercontent.com/5acae0cd4b5806bc2bce3338/dbeff06b-5575-4feb-9a78-ae89abf113e5)

### Additional features

It would be good to have a version that is able to be used with dark backgrounds where the focus is similarly on the right hand side of the image.

The styling for the desktop version is available on [Zeroheight](https://zeroheight.com/17lwnkf17/p/1716a8). Font sizes, breakpoints etc. remain the same, just the text changes to white with a black shadow, and a button suitable for a dark background is used instead.

![Screen Shot 2019-05-31 at 3.37.54 pm.png](https://images.zenhubusercontent.com/5acae0cd4b5806bc2bce3338/3d175936-52de-4798-8165-63bc20a85296)

**Comment by gepifanio** [comment]
https://github.com/unimelb/pattern-lib/pull/1139
