### ISSUE TITLE
[BUG] Section focus box btn is full width

### ISSUE THREAD

**Issue by dkevey** [unimelb/pattern-lib#1144]
## Current behaviour
The button on the section with focus box is displaying full width. 

![image](https://user-images.githubusercontent.com/1305804/58844093-fb50ed00-86b8-11e9-970c-c13f7230ab99.png)
https://pattern-lib-unimelb.netlify.com/?selectedKind=Section%2FFocus&selectedStory=With%20button&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel

## Expected behaviour
Button should look like this:
![image](https://user-images.githubusercontent.com/1305804/58844088-f2601b80-86b8-11e9-82a9-5732c29dab46.png)

See pattern-lib version at April 17:
https://5cb70699490c290008a1cb24--pattern-lib-unimelb.netlify.com/?selectedKind=Section%2FFocus&selectedStory=With%20button&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel

## Possible solution
Suspect that it changed in update to mobile enhancement. 

Full report of usage in CMS (160 instances) https://matrix-cms.unimelb.edu.au/reports/content-templates/section-with-focus 

Also need to consider FFAM overrides: https://finearts-music.unimelb.edu.au/about-us

**Comment by gepifanio** [comment]
@dkevey PR: https://github.com/unimelb/pattern-lib/pull/1148
