### ISSUE TITLE
Standardise `size` prop values

### ISSUE THREAD

**Issue by TimMansell** [unimelb/pattern-lib#1156]
## Expected behaviour

Should all use the same values (where applicable)

xxs
xs
sm
md
lg
xl
xxl

## Current behaviour

Different components use different values for size.  For example:

`size="sm"`
`size="small"`
`size="sml"`

all denote a small variation.

Impacted components:

- [ ] ButtonIcon
- [ ] variables
- [ ] FocusWrapper
- [ ] ContentBlock
- [ ] CardFocusBox
- [ ] InPageNavigation (FocusWrapper)
- [ ] Testimonials (FocusWrapper)
- [ ] Tidy up Headings with validator

**Comment by gepifanio** [comment]
PR: https://github.com/unimelb/pattern-lib/pull/1162
