### ISSUE TITLE
[Bug] Strange animation behaviour when using global search on maps.unimelb

### ISSUE THREAD

**Issue by jaredh-um** [unimelb/pattern-lib#1157]
## Expected behaviour

When activating the global search in the top right hand corner of the page, a white overlay fades in and the search form animates in from the top of the screen.

## Current behaviour

On [maps.unimelb](https://maps.unimelb.edu.au) there appears to be some kind of JS conflict with the mazemaps JS as the animation is being hijacked, resulting in some kind of WebGL spinning strobing animation.

## Steps to reproduce
1. Go to [maps.unimelb.edu.au](https://maps.unimelb.edu.au)
2. Click the search icon in the top right hand corner
3. ????
4. Profit

**Comment by woowoowoo** [comment]
I've realised where this comes from.

The geolocate icon on a map, is a graphic which rotates 90° when clicked, and keeps doing that, creating a spinning progress icon until another js event comes through the map library.

Why it's affecting the search backdrop is anybody's guess. I expect some tightening of the event/action will sort it out.

**Comment by TimMansell** [comment]
I have created a PR for a fix. It will be available in next release. 

#1248
