### ISSUE TITLE
Console issues

### ISSUE THREAD

**Issue by gepifanio** [unimelb/pattern-lib#1170]
## Expected behaviour
No console issues.

## Current behaviour
![image.png](https://images.zenhubusercontent.com/5be8f6294f44731953087568/5e10c4a8-6cde-466b-8296-79c478e5d114)

**Comment by dyarmachok** [comment]
Hi 
I tried to reproduce the issue according to screenshot and components used for, but have no luck 
If you can share more details how to reproduce it, it will be very helpfull for me to move on with it

**Comment by gepifanio** [comment]
Hello @dyarmachok, this issue is quite old and is outdated, sorry about that, but we still do have console log issues/warnings going on, and would be good to have that fixed:

![image](https://user-images.githubusercontent.com/16002934/112555985-6420d080-8e1d-11eb-968f-a10b2d115063.png)
