### ISSUE TITLE
Investigate relative file importing

### ISSUE THREAD

**Issue by TimMansell** [unimelb/pattern-lib#1181]
Instead of needing to enter the required parent levels `../` use a relative importing process such as `~` using webpack.

This will make it easier to move components around and not need to worry about the correct relative path.

## Expected behaviour

```
import PageHeader from '~/components/header/PageHeader.vue';
```

## Current behaviour

```
import PageHeader from '../../components/header/PageHeader.vue';
```

**Comment by gepifanio** [comment]
It has been done already.
