### ISSUE TITLE
Move FindACourseSpritesheet icons to Spritesheet

### ISSUE THREAD

**Issue by gepifanio** [unimelb/pattern-lib#1190]
## Expected behaviour

Icons inside of the FindACourseSpritesheet should be moved to the Spritesheet.

**Comment by FPG-Github** [comment]
Hey @gepifanio - just to confirm is this is about rolling the second SVG sprite sheet that is bundled with the MegaMenu code into the base Pattern Lib SVG sprite sheet?

![image](https://user-images.githubusercontent.com/4566277/60691061-1c9f3600-9f10-11e9-8607-af157d0311c5.png)

FYI that I am wrapping the MegaMenu setup into the base CMS templates, so just thinking through how best to manage the second SVG and CSS overrides that currently get bundled with the Mega menu, an issue that would disappear if you combine the two.
