### ISSUE TITLE
Fix Tabs snapshot test

### ISSUE THREAD

**Issue by TimMansell** [unimelb/pattern-lib#1195]
## Steps to reproduce

1.
2.
3.

### Affected browsers

- [ ] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] IE 11
- [ ] Safari 8+
- [ ] iOS 8.4+
- [ ] Android 4.4+

**Comment by jaredhenderson** [comment]
Hasn't been followed up for 2 years and is probably way out of date by now. Closing.
