### ISSUE TITLE
Button updates

### ISSUE THREAD

**Issue by TimMansell** [unimelb/pattern-lib#1205]
There are a few undocumented buttons types/modifiers that I've come across in Storybook that aren't under the Buttons category. It would be good to round these up and have them listed in the same category so we can keep track of them.

`btn--hard` class on this [Accordion example](https://pattern-lib-unimelb.netlify.com/?selectedKind=Accordion&selectedStory=Enquiry%20%28toggle%20block%29&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel)

`.page-header__darken--o50 .page-header .btn` and `.page-header__darken--o25 .page-header .btn` on Campaign banners [50%](https://pattern-lib-unimelb.netlify.com/?selectedKind=Page%20%2F%20Header%20%2F%20Level%201&selectedStory=Homepage%20campaign%20%28overlay%2C%2050%25%20opacity%29&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel) and [25%](https://pattern-lib-unimelb.netlify.com/?selectedKind=Page%20%2F%20Header%20%2F%20Level%201&selectedStory=Homepage%20campaign%20%28overlay%2C%2025%25%20opacity%29&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel) overlay

- [x] make font-weight bold
- [x] reinstatement of border opacity change on hover (from 30% to 100%)
- [x] modification of transition value to affect all properties
- [x] tweaks to border-radius size

Button mapping

Button (Navy) = cta
Button (Navy Outline) = default
Button (White) = `.btn--hard`
Button (White outline) = inverted
Button (Campaign banner) = `.page-header__darken`

**Comment by jonathan-doc** [comment]
Hey @TimMansell @gepifanio, the latest iterations of the buttons are up on [zeroheight](https://zeroheight.com/17lwnkf17/p/378949/b/97d0b8). I've included the CSS colour properties for each of the states to make things a bit easier :)

Button mapping:

Navy (Solid) = cta
Navy (Outline) = default
White (Solid) = .btn--hard
White (Outline) = inverted
Campaign = .page-header__darken

**Comment by TimMansell** [comment]
Done.
