### ISSUE TITLE
Styling conflicts in general

### ISSUE THREAD

**Issue by woowoowoo** [unimelb/pattern-lib#1250]
Hi again,
not a specific issue - though it was triggered by one. The latest update to the MCE brought with it a new class - or at least a new rule to an existing class: .filter

Perhaps I see this more than others, because I use third party libraries for maps, and pageup (jobs), but when we use generic words for classes, it's almost inevitable that someone else will have used those same words for their own styling, or worse still, as a hook for a javascript function to target.

I'd like to see us namespace our classes to avoid such conflicts. .um-filter? I dunno, anything that will insulate our styles from the effects of others, and vice versa.

**Comment by jaredh-um** [comment]
This issue won't be resolved in Gen 2, but Gen 4 will have prefixed classes in a similar style to that suggested - at this stage it is `uom-`.
