### ISSUE TITLE
[BUG] Typography heading bugs

### ISSUE THREAD

**Issue by jaredh-um** [unimelb/pattern-lib#1254]
## Current behaviour

We recently adjusted the character spacing on Noto Serif headings to be slightly reduced from the default so give a more condensed, readable look. Generally this has worked well, but there are a couple of places it isn't implemented or needs to be reviewed.

eg; the H2 on the [News article with categories](https://pattern-lib-unimelb.netlify.com/?selectedKind=Article&selectedStory=News%20article%20with%20categories&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel) component is using Source Sans Pro and should not have the letter-spacing value changed.

![Screen Shot 2019-08-22 at 1.06.53 pm.png](https://images.zenhubusercontent.com/5acae0cd4b5806bc2bce3338/24176b17-57d8-4c15-be01-d29f7fa9d24d)

Additionally, the letter-spacing values are cascading down to other heading sizes where a letter-spacing value has not already been specified.

![Screen Shot 2019-08-29 at 3 00 41 pm](https://user-images.githubusercontent.com/34703139/63911576-1dff6180-ca6e-11e9-9186-a6412977b1b2.png)

### Suggested changes

- [ ] Adjust letter-spacing value for Noto Serif H1 and H2 headings to be `-1px` instead of `-.125rem` as it is slightly too much (especially when body font-size changes to 18px)
- [ ] Where headings use Source Sans Pro, there should be no letter-spacing adjustment. Letter-spacing should be set manually to defaults if there is not one specified so the value is not inherited from elsewhere
- [ ] Maybe the Article component needs adjusting to not use the 'heading-cards' class on the H2?

**Comment by woowoowoo** [comment]
I would like to see way more specificity than even this. Maybe first-child or immediate inheritance could be used to make sure it only effects the intended headings. The effect still cascades into all sorts of unexpected places. (that's a bookmarklet)

![Screen Shot 2019-08-30 at 9 45 24 am](https://user-images.githubusercontent.com/848310/63983855-f2cb4f80-cb0b-11e9-96e2-13ca20278a8c.png)

Also: _more … readable_. I'd argue that, (though I have no evidence to hand), any time you cause characters to 'crash', you are decreasing legibility. Also, from my understanding of the theory, the decrease in word spacing that has occurred as a result of decreasing the letter spacing is also detrimental to legibility. Especially so for readers with cognitive disabilities.

**Comment by jaredh-um** [comment]
I'd agree that how headings are structured and manipulated in the CSS needs to be looked at, because this is not the first time a slight change has had unintended cascading effects.

You could argue the opposite for characters with too much letter spacing. The spacing was not meant to be reduced by the amount that it is (and was only intended to be for H1s and H2s) so we'll see what it looks like when it's up to date.

**Comment by woowoowoo** [comment]
Certainly desktop fonts are looser in general than the old typographic systems, and web fonts are pretty terribly spaced, but I think those headings are still too tight. (source: kerning typefaces was part of my job back in the 80's ;-)

**Comment by TimMansell** [comment]
> * [ ]  Maybe the Article component needs adjusting to not use the 'heading-cards' class on the H2?

We should do that.

**Comment by TimMansell** [comment]
> I would like to see way more specificity than even this. Maybe first-child or immediate inheritance could be used to make sure it only effects the intended headings. The effect still cascades into all sorts of unexpected places. (that's a bookmarklet)
> 
> ![Screen Shot 2019-08-30 at 9 45 24 am](https://user-images.githubusercontent.com/848310/63983855-f2cb4f80-cb0b-11e9-96e2-13ca20278a8c.png)
> 
> Also: _more … readable_. I'd argue that, (though I have no evidence to hand), any time you cause characters to 'crash', you are decreasing legibility. Also, from my understanding of the theory, the decrease in word spacing that has occurred as a result of decreasing the letter spacing is also detrimental to legibility. Especially so for readers with cognitive disabilities.

Unfortunately it's not that simple. `:first-child` will only target the first instance of that element and `>` will miss elements that should be styled.  Sample below.

https://jsfiddle.net/593r7m6L/

can you provide some pages that are being greatly affected and I'll see if theres a solution I can come up with.

**Comment by jaredh-um** [comment]
https://brandhub.unimelb.edu.au/competition/competition is one

**Comment by TimMansell** [comment]
@jaredh-um, can you check these pages:

https://deploy-preview-1268--pattern-lib-unimelb.netlify.com/?selectedKind=Typography%20%28deprecated%29&selectedStory=Heading%20elements&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel

https://deploy-preview-1268--pattern-lib-unimelb.netlify.com/?selectedKind=Typography%20%28deprecated%29&selectedStory=Heading%20classes&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel

https://deploy-preview-1268--pattern-lib-unimelb.netlify.com/?selectedKind=Typography&selectedStory=Titles&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel

https://deploy-preview-1268--pattern-lib-unimelb.netlify.com/?selectedKind=Typography&selectedStory=Titles&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel

https://deploy-preview-1268--pattern-lib-unimelb.netlify.com/?selectedKind=Typography&selectedStory=Lead%20paragraph&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel

**Comment by woowoowoo** [comment]
A gentler approach would minimise the negative effects of leakage - my feeling is that: letter-spacing: -.05rem; is about right, but that you should also consider reversing the effect this has on word spacing with: word-spacing: 0.05rem;

**Comment by TimMansell** [comment]
> A gentler approach would minimise the negative effects of leakage - my feeling is that: letter-spacing: -.05rem; is about right, but that you should also consider reversing the effect this has on word spacing with: word-spacing: 0.05rem;

Agreed. Minimising effect would be ideal.

**Comment by jaredh-um** [comment]
I'm fine with that approach. The `lead` classes require the `letter-spacing: normal` to be retained in the general H3-H6 classes as they're being overridden otherwise:

**Comment by gepifanio** [comment]
Changes have been applied through the PR: https://github.com/unimelb/pattern-lib/pull/1268

**Comment by gepifanio** [comment]
Done already.
