### ISSUE TITLE
IE Scrollbar Styling

### ISSUE THREAD

**Issue by jonathan-doc** [unimelb/pattern-lib#1265]
The default IE scrollbar stands out quite a bit, so we've themed it to match the UoM brand.

Set:
- [x] `-ms-scrollbar-face-color` to **Navy Mid 1** (#ABBED5)
- [x] `-ms-scrollbar-arrow-color` to **Navy Main** (#094183)
- [x] `-ms-scrollbar-track-color` to **Navy Light** (#F2F5F9)
- [x] `-ms-scrollbar-shadow-color` to **Navy Light** (#F2F5F9)

![ie11-scrollbar-styling-light.png](https://images.zenhubusercontent.com/5c6f79e81e498d06ff8b58ba/07024de6-8a41-4149-8775-858a79f45904)
![ie11-scrollbar-styling-dark.png](https://images.zenhubusercontent.com/5c6f79e81e498d06ff8b58ba/cbb81aa3-983e-42ab-9639-d599714972c2)

Breakdown of scrollbar properties:
![ie11-scrollbar-properties.jpg](https://images.zenhubusercontent.com/5c6f79e81e498d06ff8b58ba/96d10e41-b276-4eed-b35e-2fd25df3fbb2)

**Comment by gepifanio** [comment]
PR: https://github.com/unimelb/pattern-lib/pull/1215

**Comment by gepifanio** [comment]
We no longer support IE11
