### ISSUE TITLE
[BUG] In-page navigation anchoring when browsing link from another page

### ISSUE THREAD

**Issue by TimMansell** [unimelb/pattern-lib#1270]
If the user clicks on a link to go to a page that uses `in page nav` the page correctly jumps to the correct section but the dropdown covers the title.

## Expected behaviour

![Screen Shot 2019-08-30 at 10 02 24 am](https://user-images.githubusercontent.com/1926461/63984178-48542c00-cb0d-11e9-89b9-660d861eefa3.png)

## Current behaviour

![Screen Shot 2019-08-30 at 10 02 14 am](https://user-images.githubusercontent.com/1926461/63984180-4be7b300-cb0d-11e9-8c8b-54a6f5efedc7.png)

## Steps to reproduce

1. https://finearts-music.unimelb.edu.au/faqs#navigation-timetables

**Comment by gepifanio** [comment]
I have tested and seems working as expected, which do you had this issue?

**Comment by TimMansell** [comment]
Issues is still there.  Happens only on page load with a #hash in url

https://finearts-music.unimelb.edu.au/faqs#navigation-timetables

**Comment by gepifanio** [comment]
Hey @TimMansell, I was trying to solve this problem, however is not that simple, JS has that `hashchange` event, but it only triggers when the hash actually change, if is the first hit on the page, doesn't trigger that, so I cannot identify if the user is going through the page using hash navigation. Do you know another way that we could do that?
