### ISSUE TITLE
[bug] tab indicator floating about megamenu on course pages

### ISSUE THREAD

**Issue by gepifanio** [unimelb/pattern-lib#1280]
@kebfrf commented on [Tue Jul 23 2019](https://github.com/unimelb/find-a-course/issues/1363)

Reported by Camryn Rothenbury: 
-found when viewed on Chrome when browser width > 1600px: "the current tab indicator is floating on top of the super menu.
 
The element a.nav__link--current::after should have a lower z-index (100 appears to fix it) or alternatively the super menu should have a higher z-index. This is affecting Chrome on browser width 1600px or wider." 
![image.png](https://images.zenhubusercontent.com/5ab48f164b5806bc2bcc1060/d471e877-3e13-4e54-b84c-389e292194f1)

- I have been able to reproduce on https://study.unimelb.edu.au/find/courses/undergraduate/bachelor-of-arts/ on Chrome and Macbook Pro (fire edition), and on Firefox and Mac. 
- is this a pattern lib issue? 

---

@gepifanio commented on [Wed Sep 04 2019](https://github.com/unimelb/find-a-course/issues/1363#issuecomment-527730523)

Yes, it is a pattern-lib issue, I will move this ticket to the pattern-lib repo and work on that.

**Comment by TimMansell** [comment]
Done in 4.18.2
