### ISSUE TITLE
[CHORE] No follow for phone number links in footer

### ISSUE THREAD

**Issue by kebfrf** [unimelb/pattern-lib#1295]
The links to phone numbers are being followed by search engines, which is causing an error because they're not urls! 

add rel=nofollow to the following phone links on https://github.com/unimelb/pattern-lib/blob/dev/components/footer/PageFooterUpper.vue

line 137: link to 13melb
line 142: link to international help number

**Comment by gepifanio** [comment]
PR: https://github.com/unimelb/pattern-lib/pull/1342
