### ISSUE TITLE
[BUG] Card news column on Firefox

### ISSUE THREAD

**Issue by gepifanio** [unimelb/pattern-lib#1297]
## Expected behaviour

Card news column to be working with firefox ESR 52.7.3

## Current behaviour

![image (3)](https://user-images.githubusercontent.com/16002934/65209521-c0de5500-dadb-11e9-8ba0-60638b04f1e2.png)

## Steps to reproduce

https://pattern-lib-unimelb.netlify.com/?selectedKind=Cards%2FNews&selectedStory=3%20Column&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel

**Comment by jaredh-um** [comment]
This version of Firefox is no longer supported. Closing.
