### ISSUE TITLE
[BUG] Events card showing wrong link colour when bg-inverted is used

### ISSUE THREAD

**Issue by dkevey** [unimelb/pattern-lib#1308]
card__header link colour is showing as `color: #7cbdcd;` when it should be `color: #094183;` when the background section colour is set to `bg-inverted`. Looks like a style bleeding through from something else.

https://matrix-cms.unimelb.edu.au/web/mce/content-templates/event-listing-local-assets/_recache

![image](https://user-images.githubusercontent.com/1305804/66285877-81f13180-e91a-11e9-98e9-b51f20670e7c.png)

Should look like this: 
![image](https://user-images.githubusercontent.com/1305804/66286014-18255780-e91b-11e9-99ed-8309efe41f80.png)

**Comment by dkevey** [comment]
Have added a CSS override for the moment:
```
/* ======== Bug #1308 event listing header link in bg-inverted ========= */
.bg-inverted .card--generic a {color: #094183;}
```

**Comment by gepifanio** [comment]
Should be addressed in the ticket for matrix CSS overrides. #1325
