### ISSUE TITLE
[BUG] Heading on features and benefits panel inheriting H5 properties

### ISSUE THREAD

**Issue by jaredh-um** [unimelb/pattern-lib#1318]
### Expected

![Screen Shot 2019-10-15 at 2.40.41 pm.png](https://images.zenhubusercontent.com/5acae0cd4b5806bc2bce3338/90c8dc2d-1670-4a49-95fe-72ffd7931acc)

### Reality

![Screen Shot 2019-10-15 at 2.40.50 pm.png](https://images.zenhubusercontent.com/5acae0cd4b5806bc2bce3338/608651e5-028f-4990-ad3c-1478276fcb63)

### Proposed fix
Text-transform should be set to standard case.

**Comment by TimMansell** [comment]
Hi @jaredh-um which page did you see this on?

**Comment by jaredh-um** [comment]
@TimMansell Donna's [documentation page](https://matrix-cms.unimelb.edu.au/web/mce/content-templates/features-panel)

**Comment by TimMansell** [comment]
Hi @dkevey, was there a reason for using an `<h5>` compared to `<h3>`?  `<h5>` has uppercase assigned to it.

Was this an a11y change that should be updated in pattern lib too?

**Comment by jaredh-um** [comment]
This issue seems to have been resolved. Closing.
