### ISSUE TITLE
[CHORE] Migrate MegaMenu matrix css overrides

### ISSUE THREAD

**Issue by TimMansell** [unimelb/pattern-lib#1319]
Matrix CMS has some CSS overrides for the `mega menu`.  Investigate if they are still required and migrate to pattern lib if needed.

![Screen Shot 2019-10-17 at 11 12 34 am](https://user-images.githubusercontent.com/1926461/66968073-16078980-f0cf-11e9-8b09-49993755b1c0.png)

## Steps to reproduce

1. https://study.unimelb.edu.au/
2. view-source
3. Lines `~83` - `~115`

**Comment by gepifanio** [comment]
Should be addressed in the ticket to migrate matrix css overrides.
