### ISSUE TITLE
[CHORE] Migrate Figure matrix css overrides 

### ISSUE THREAD

**Issue by TimMansell** [unimelb/pattern-lib#1320]
Matrix CMS has some CSS overrides for the `Figure`. Investigate if they are still required and migrate to pattern lib if needed.

![Screen Shot 2019-10-17 at 11 14 33 am](https://user-images.githubusercontent.com/1926461/66968124-58c96180-f0cf-11e9-9651-15aa42d955b3.png)

## Steps to reproduce

1. https://study.unimelb.edu.au/
2. view-source
3. Lines `~83` - `~115`

**Comment by gepifanio** [comment]
Change already done in pattern-lib
