### ISSUE TITLE
[CHORE] Migrate Article Matrix CSS overrides

### ISSUE THREAD

**Issue by TimMansell** [unimelb/pattern-lib#1321]
Matrix CMS has some CSS overrides for `Articles`. Investigate if they are still required and migrate to pattern lib if needed.

## Steps to reproduce

1. https://matrix-cms.unimelb.edu.au/design/css/uom-mce.css?v=0.1.46
2. Look for /* ========== Article styles =========== */

**Comment by gepifanio** [comment]
Should be addressed in the ticket matrix CSS overrides. #1325
