### ISSUE TITLE
[CHORE] Migrate Event Listing Matrix CSS overrides

### ISSUE THREAD

**Issue by TimMansell** [unimelb/pattern-lib#1325]
Matrix CMS has some CSS overrides for `Event listing`. Investigate if they are still required and migrate to pattern lib if needed.

## Steps to reproduce

1. https://matrix-cms.unimelb.edu.au/design/css/uom-mce.css?v=0.1.46
2. Look for `/* ======== Bug #1308 event listing header link in bg-inverted ========= */`

**Comment by gepifanio** [comment]
Should be addressed in the ticket matrix CSS overrides. https://github.com/unimelb/pattern-lib/issues/903
