### ISSUE TITLE
[CHORE] Migrate IE fixes matrix css overrides

### ISSUE THREAD

**Issue by TimMansell** [unimelb/pattern-lib#1326]
Matrix CMS has some CSS overrides for `IE fixes`. Investigate if they are still required and migrate to pattern lib if needed.

## Steps to reproduce

1. https://matrix-cms.unimelb.edu.au/design/css/uom-mce.css?v=0.1.46
2. Look for `/* Fixes IE issue with backgrounds. Will be added to future rebrand versions */` and `/* Fixed IE issue with cards */`

**Comment by gepifanio** [comment]
We no longer support IE11
