### ISSUE TITLE
[CHORE] Migrate checklist matrix css overrides

### ISSUE THREAD

**Issue by TimMansell** [unimelb/pattern-lib#1327]
Matrix CMS has some CSS overrides for `checklist`. Investigate if they are still required and migrate to pattern lib if needed.

## Steps to reproduce

1. https://matrix-cms.unimelb.edu.au/design/css/uom-mce.css?v=0.1.46
2. Look for `/* fix up padding on checklist items */`

**Comment by gepifanio** [comment]
Should be addressed in the ticket matrix CSS overrides. https://github.com/unimelb/pattern-lib/issues/903
