### ISSUE TITLE
[CHORE] Migrate card focus box matrix css overrides

### ISSUE THREAD

**Issue by TimMansell** [unimelb/pattern-lib#1328]
Matrix CMS has some CSS overrides for `card focus box` Investigate if they are still required and migrate to pattern lib if needed.

## Steps to reproduce

1. https://matrix-cms.unimelb.edu.au/design/css/uom-mce.css?v=0.1.46
2. Look for `/* Issue #1144 reduce button width from 100% to 50% */`

**Comment by gepifanio** [comment]
Should be addressed in the ticket matrix CSS overrides. https://github.com/unimelb/pattern-lib/issues/903
