### ISSUE TITLE
Image gallery and Footer z-index problems

### ISSUE THREAD

**Issue by woowoowoo** [unimelb/pattern-lib#1333]
The footer appears higher in the stacking order than the image gallery, causing it to obscure images when the image gallery is close to the bottom of the page and the footer is in view.

Example URL: https://about.unimelb.edu.au/priorities-and-partnerships/fishermans-bend

![Screen Shot 2019-10-28 at 10 57 07 am](https://user-images.githubusercontent.com/848310/67644035-ea5b8d80-f971-11e9-830e-9260e92cb003.png)

**Comment by TimMansell** [comment]
Has been fixed and included in release [5.1.1](https://github.com/unimelb/pattern-lib/releases/tag/v5.1.1)
