### ISSUE TITLE
Strategy and Leadership link in footer is (was) a 404

### ISSUE THREAD

**Issue by woowoowoo** [unimelb/pattern-lib#1338]
Someone made a change to the URL of the page at:
https://about.unimelb.edu.au/strategy-and-leadership
There's a link to it from the standard footer.

I've set up a remap, so it no longer ends in error, but the URL should be updated to:
https://about.unimelb.edu.au/strategy

**Comment by woowoowoo** [comment]
Actually, just noticed the page title is now Strategy and Governance, so I guess the link text should also be updated.

**Comment by TimMansell** [comment]
This has been fixed and will be released in v5.12.0
