### ISSUE TITLE
Global footer link addition

### ISSUE THREAD

**Issue by jaredh-um** [unimelb/pattern-lib#1340]
#### Details

A request has come in to add 'Accommodation' to a section of the global footer.

Link text: Accommodation
Link URL: https://study.unimelb.edu.au/your-experience/accommodation
Link location: ![Screen Shot 2019-11-11 at 1.16.16 pm.png](https://images.zenhubusercontent.com/5acae0cd4b5806bc2bce3338/486bafe7-7c56-4b49-909e-6e46d5849a25)

(after 'Connect with us')

#### Implementation
- [x] Please implement new footer link as per above details

**Comment by gepifanio** [comment]
PR: https://github.com/unimelb/pattern-lib/pull/1342
