### ISSUE TITLE
[Bug] Gen 2 buttons have visited state attributes

### ISSUE THREAD

**Issue by jaredh-um** [unimelb/pattern-lib#1349]
#### Currently
It seems that some of our button classes have attributes assigned to their visited state. In the example below, the button should be white and change to light blue on hover, but it is presenting as light blue because the URL has been visited before.

Visible on the documentation site for the [features panel](https://matrix-cms.unimelb.edu.au/web/mce/content-templates/features-panel/_nocache?cct=dev)

![image.png](https://images.zenhubusercontent.com/5acae0cd4b5806bc2bce3338/5b679b0d-c312-4831-8de9-209f67e3f179)

#### Proposed solution
Buttons should not have any visited attributes.

- [ ] Remove .btn:visited, btn--secondary:visited, etc. attributes for all button types

**Comment by TimMansell** [comment]
Hi @jaredh-um, if we remove the `:visited` for the buttons then it will inherit the default `a:visited`

My suggestion would be to update `:visited` to match the default state of the button.

**Comment by jaredh-um** [comment]
@TimMansell oh right, I see. Are you able to move the pseudo selectors for the :visited states around so that they're clustered with the default styling rather than the hover and focus states?

**Comment by TimMansell** [comment]
yep

**Comment by TimMansell** [comment]
PR https://github.com/unimelb/pattern-lib/pull/1366
