### ISSUE TITLE
Remove focus marks from image listing components

### ISSUE THREAD

**Issue by jonathan-doc** [unimelb/pattern-lib#1390]
Focus marks are being phased out, and at this stage we're starting with image listings.

https://pattern-lib-unimelb.netlify.com/?selectedKind=Listing%2FImage%20Listing&selectedStory=Three%20Column&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel

**Comment by jaredh-um** [comment]
This is not a priority, and the areas this [component are listed](https://matrix-cms.unimelb.edu.au/reports/content-templates-reports/images) in are quite corporate so I'd be hesitant to prioritise stripping these out.
