### ISSUE TITLE
[BUG] SVG icon used on events page template too small

### ISSUE THREAD

**Issue by dkevey** [unimelb/pattern-lib#1399]
If too much text is entered in the location field on the study events page template the icon gets squished.

## Expected behaviour
Icon should remain consistant size regardless of content entered. Length of content is unknown due to overseas countries having long addresses.

example:  https://study.unimelb.edu.au/connect-with-us/events-for-future-students/all-events-listing/interstate-student-information-day/

![image](https://user-images.githubusercontent.com/1305804/75409448-d4d09180-596c-11ea-94bb-bbca2362c314.png)

**Comment by TimMansell** [comment]
Done. Included in `v5.5.4`

Can you add a class `sidebar__list-info` to a `div`

Current:
```
 <div>
   <h4 class="sidebar__list-title">...</h4>
```

New:
```
 <div class="sidebar__list-info">
   <h4 class="sidebar__list-title">...</h4>
```
