### ISSUE TITLE
[Enhancement] Remove 'About us' from Key areas section of homepage

### ISSUE THREAD

**Issue by jaredh-um** [unimelb/pattern-lib#1443]
### Currently
Currently 'About us' is featured in the welcome area as one of the 'key areas' quicklinks.

<img width="427" alt="Screen Shot 2020-05-13 at 1 33 10 pm" src="https://user-images.githubusercontent.com/34703139/81768607-c5e68d80-951e-11ea-85fc-581bb7d92fab.png">

### Proposed change
A change has been requested to remove the 'About us' link from this section in order to keep primary homepage CTA areas for higher-value assets. About us is still accessible from the main hamburger menu on the homepage, and footer on every standard UoM page.

- [ ] Remove (or hide) the 'About us' button from quicklinks in welcome section of the homepage

**Comment by gepifanio** [comment]
Hey, @jaredh-um so this ticket doesn't require frontend development as this component could easily just be tweaked the data from not receiving 4 objects or deleting the HTML where it renders the last link which is the `about us`.

[Quick link menu](https://pattern-lib-unimelb.netlify.app/?selectedKind=Quick%20Link%20Menu&selectedStory=Alternate%20D&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel)

**Comment by jaredh-um** [comment]
@gepifanio sure thing, I'll let CMS know.
