### ISSUE TITLE
[Accessibility] Link uses general text like "Click Here" which doesn't explain link purpose.

### ISSUE THREAD

**Issue by mvaldman** [unimelb/pattern-lib#1453]
Link uses general text like "Click Here" which doesn't explain link purpose.

### Example URLs (non exhuastive)
https://study.unimelb.edu.au/find/courses/graduate/doctor-of-medicine
https://study.unimelb.edu.au/find/courses/graduate/graduate-certificate-in-tesol
https://study.unimelb.edu.au/find/courses/graduate/graduate-diploma-in-global-competition-and-consumer-law/the-experience/
https://study.unimelb.edu.au/find/courses/graduate/graduate-diploma-in-veterinary-professional-leadership-and-management

**Comment by mvaldman** [comment]
This issue has been added to the Accessibility Issues page: https://matrix-cms.unimelb.edu.au/study-fac/content/review/accessibility

**Comment by jaredhenderson** [comment]
Relates to content. Closing.
