### ISSUE TITLE
[Feature] Add video bullet point list to typography styles

### ISSUE THREAD

**Issue by jaredh-um** [unimelb/pattern-lib#1507]
#### What is this feature?

A new list style which is used to display a list of text links with a video play icon as the bullet.

![Screen Shot 2020-09-10 at 12.08.58 pm.png](https://images.zenhubusercontent.com/5acae0cd4b5806bc2bce3338/50f4acbd-e11b-4e68-af96-e36934ce698f)

A temporary version has been implemented in the Matrix global overrides file, and is currently [documented](https://matrix-cms.unimelb.edu.au/web/mce/styling-content/typography#lists-variants) on the Matrix resources site.

A live page that uses this example is the [UG post-Open Days events page](https://study.unimelb.edu.au/undergraduate/events)

#### What is required

This style needs to be properly integrated with the other listing styles.

- class name currently in use on Matrix is `video-list`
- should be able to be applied to a `ul` group for ease of use, and also an `li` item for mixed lists
- icon needs to be added to the gen 2 spritesheet and colour able to be set by CSS as with other icons
- spacing, alignment etc. should mirror or complement existing styles

Once this style is made available in a release and Matrix is updated, the current overrides should be removed from the Matrix global overrides file.

**Comment by gepifanio** [comment]
PR: https://github.com/unimelb/pattern-lib/pull/1508

**Comment by jaredh-um** [comment]
Do you know if this style is being used anywhere at the moment @gepifanio? I think there's quite a bit of work to get it right, should be considered as a future feature for Gen 4 (custom/coloured bullets)

**Comment by gepifanio** [comment]
@jaredh-um it's not used anywhere, but it have been implemented in the PR #1508, now we just need to figure it out, if we move forward merging or just close the issue and PR.

**Comment by jaredh-um** [comment]
I think it is probably more work for us to make this available at the moment, particularly since it is not in use - we would need to account for different background colours, etc. I think we should close this for now and address later in Gen 4.

**Comment by gepifanio** [comment]
Closing issue.
