### ISSUE TITLE
[BUG] Social links in global footer stacked in Safari

### ISSUE THREAD

**Issue by woowoowoo** [unimelb/pattern-lib#1548]
Social links (FB, Twitter, LinkedIn) in the global footer are aligned vertically in Safari

## Current behaviour
![image](https://user-images.githubusercontent.com/848310/89252903-72d43080-d65e-11ea-9466-fec2943dafa9.png)

## Steps to reproduce
Screenshot shows the same page: https://www.unimelb.edu.au/global-challenge in Google Chrome (left), and Safari (right). Horizontal alignment (Chrome) is correct, vertical alignment (Safari) is not. Viewport width doesn't change the problem.

### Affected browsers
I haven't tested widely.
- [ ] Chrome
- [ ] Firefox
- [x] Safari Version 13.1.2 (15609.3.5.1.3)

**Comment by gepifanio** [comment]
Tested locally and with Andrew, its working all good 🎉
