### ISSUE TITLE
[Accessibility] CMS not in sync with pattern-lib components

### ISSUE THREAD

**Issue by gepifanio** [unimelb/pattern-lib#1586]
After some work with accessibility, we could notice some pattern-lib components are not in sync with `CMS CCT's`.

- For example, we removed the `role="presentation"` is not being used anymore. it was done in the PR: #1532, however, is not updated in the CMS it was released in the version `v8.2.0` https://github.com/unimelb/pattern-lib/releases 

- We need somehow to make sure that every fix/change and or chore we do in pattern-lib, either markup change, or anything else related is up to date on the CMS side as well, not only the version number, otherwise, the fixes not gonna go through the website live.

- Another example would be the quick links component:
https://matrix-cms.unimelb.edu.au/web/mce/content-templates/menu their markup is not the same as we currently have regarding the SVG icons - https://pattern-lib-unimelb.netlify.app/?selectedKind=Quick%20Link%20Menu&selectedStory=Default&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel

**Comment by dkevey** [comment]
RE: the `role="presentation"` I've picked up on this some time ago and have been replacing as I need to in the CTs. I try and check all new CTs via the https://validator.w3.org and Siteimprove / Wave accessibility checkers. It's highly likely that earlier CTs are still using earlier code. Unless these are clearly documented in the Release notes or reported as issues, it's likely they will be missed in the updates.

**Comment by dkevey** [comment]
as for https://matrix-cms.unimelb.edu.au/web/mce/content-templates/menu and  https://pattern-lib-unimelb.netlify.app/?selectedKind=Quick%20Link%20Menu&selectedStory=Default&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel can you provide an example of the markup that is wrong please as I can't see the difference

**Comment by gepifanio** [comment]
In the quick links menu example, the `chevron` icons should be using `aria-hidden="true"`

**Comment by dkevey** [comment]
sorry I can't see where that change is reflected in the release notes https://github.com/unimelb/pattern-lib/releases ?

**Comment by gepifanio** [comment]
- Icons aria-label fix was in the PR: #1063  and in the release: https://github.com/unimelb/pattern-lib/releases/tag/v4.4.5
- ButtonIcon has been added `aria-hidden` in the release https://github.com/unimelb/pattern-lib/releases/tag/v4.11.0 in the PR: #1197

**Comment by dkevey** [comment]
I've gotta say, those release notes are not easy to read

**Comment by gepifanio** [comment]
Yes, we need to figure out a way to better explain and make sure we all in sync
