### ISSUE TITLE
[BUG] Cards with inverted background getting wrong colour for subtitle and description

### ISSUE THREAD

**Issue by gepifanio** [unimelb/pattern-lib#1591]
https://pattern-lib-unimelb.netlify.app/?selectedKind=Cards%2FGenericCard&selectedStory=BG%20inverted&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel

**Comment by jaredhenderson** [comment]
Looks to have been addressed by the PR above. Closing.
