### ISSUE TITLE
[Bug] Video poster not filling its container

### ISSUE THREAD

**Issue by jaredhenderson** [unimelb/pattern-lib#1639]
## Currently

The landscape video component poster is not filling its container. [Example page](https://study.unimelb.edu.au/study-refresh-2021/study-landing-page/_nocache)

![Screen Shot 2021-05-27 at 11.15.23 am.png](https://images.zenhubusercontent.com/5acae0cd4b5806bc2bce3338/f53dea30-1b91-4d28-80ce-e0da0d52b562)

## Proposed change

We have to assume that not everyone will provide posters that meet the recommended ratio/size. 

- [ ] Image should be set to fill the full height and width of the video container, and be set to `cover` so there are no visible gaps anywhere.

**Comment by gepifanio** [comment]
PR: https://github.com/unimelb/pattern-lib/pull/1643
