### ISSUE TITLE
[Bug] Some images broken in Storybook

### ISSUE THREAD

**Issue by jaredhenderson** [unimelb/pattern-lib#1640]
## Currently

Stories that relied on local static assets seem to have become broken with the 9.4.0 release.

[Today > Campaign](https://pattern-lib-unimelb.netlify.app/?selectedKind=Today%2FCampaign&selectedStory=Default&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel)
[Today > Header](https://pattern-lib-unimelb.netlify.app/?selectedKind=Today%2FHeader&selectedStory=Default&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel)

...and potentially others, I have not checked everything.

## Proposed change

- [ ] Amend deploy/build/stories to fix broken image links issue

**Comment by gepifanio** [comment]
https://github.com/unimelb/pattern-lib/pull/1641
