### ISSUE TITLE
[a11y] SVG IDs are repeated by being injected twice

### ISSUE THREAD

**Issue by jaredhenderson** [unimelb/pattern-lib#1652]
## Currently
Gen 2 and FAC both have their own system for injecting SVGs inline to the DOM to be used dynamically by other components.

Duplication of some icons, and using the exact same ID is occurring with three icons:

- `icon-calendar`
- `icon-check`
- `icon-info`

![Screen Shot 2021-06-03 at 3.34.39 pm.png](https://images.zenhubusercontent.com/5acae0cd4b5806bc2bce3338/c09e1df7-53a8-45f1-9a97-ec50316e5f25)

## Proposed changes

- [x] Check icon files are visually identical before we consider de-deduplicating

Preferred option:
- [x] Remove duplicate icons from FAC spritesheet and use from pattern-lib instead

Second option:
- [x] Add unique icons to pattern-lib spritesheet, delete FAC spritesheet and use from one source instead of two

Third option:
- [x] Rename FAC icon IDs to `fac-icon-XYZ` to prevent ID duplications

**Comment by gepifanio** [comment]
Analyzed this issue, and chatted with @dkevey this second sprite sheet looks like it's an old sprite sitting in the CMS, which now has been removed as we don't need that anymore.
