### ISSUE TITLE
[Feature] Can we get G4 mega menu working in G2?

### ISSUE THREAD

**Issue by jaredhenderson** [unimelb/pattern-lib#1658]
## Currently
There are dev pages set up by Donna to test the implementation of the G4 mega menu in a Gen 2 site.

Reference ticket on Today JIRA: https://todaydesign.atlassian.net/browse/UOM18B-169

Test pages gen2:

https://matrix-cms.unimelb.edu.au/dev/_nocache
https://matrix-cms.unimelb.edu.au/dev/study-landing-page/undergraduate-courses
https://matrix-cms.unimelb.edu.au/dev/study-landing-page/graduate-courses
https://matrix-cms.unimelb.edu.au/dev/study-landing-page/graduate-research

param required to test: `?megatest=yes`

Test pages gen3:

https://students.unimelb.edu.au/

param required to test: `?megatest=yes` + design switcher

## To investigate
- [X] Can mega menu `div` be placed outside of main Vue `ui` div to ensure no JS conflicts?
- [X] Do issues relating to mega menu presentation (eg; visited link colours, short menus, other visual defects) simply relate to CSS cascade? Or are there more substantial conflicts occurring?
- [x] Will any potential fixes for these issues have an impact on where these menus are currently already used in Gen 3?

Principles:
- [x] Mega menu must remain functionally and visually the same when used in Gen 3 or 2
- [X] JS overlap should ideally be avoided

## Proposed changes
**Gen 4:**
- [x] fix keyboard navigation flashing 
- [x] fix mouse navigation flashing

GEN2:
![image.png](https://images.zenhubusercontent.com/5be8f6294f44731953087568/9524308b-e7fa-4c1e-a294-bffb624c1bd7)
- Gen 2 site dropdown overlay hidden

  - [x] add new z index 101 to tailwind config
  - [x] Set container child z-index to `101`

- [x] Set paragraph text colour in promo areas to white
- [x] Set visited link colour to white/whatever the link colour is
- [x] Set link background colours as per separate a11y ticket
- [x] Set paragraph text colour in promo areas to white
- [x] Promo image label needs wrap fixed so chevron doesn't go onto new line
- [x] remove unused `um:mega-menu-dropdown__primary-link` class
- [x] add alt text to the storybook images examples
- [x] Setting margin: 0 on li will apply this to ALL of Gen 2, not just the mega menu. Scope to the mega menu ONLY
- [x] Merged PR https://github.com/unimelb/Gen4/pull/43 to change `px` values to `rem`

GEN2 site white separation between mega menu top and mega menu dropdown overlay
![image.png](https://images.zenhubusercontent.com/5be8f6294f44731953087568/5020dd16-0893-4f8c-ac8b-a66c4e4ed9b0)
  - [x] add margin top 0 to mega menu dropdown active
- [x] fix keyboard tabbing inside the mega menu dropdown causes it to flash
- [x] remove unused z-index props

- Current design doesn't account for the Gen 2 18px font-size change at higher breakpoints:
  - [X] Change height from 96px to 6rem
  - [X] Adjust logo size to rems
  - [X] Adjust search button size to rems
  - [X] Adjust everything to rems

- [x] remove ike.js and add auto inject sprite from sprite loader
- [x] Remove SVG sprite icons from appearing or being display inside of the body

- [x] Remove extra padding-right from last secondary link to fix right-alignment
- [x] Search overlay blanket is currently not on a full page

**Gen 2:**
- [x] Set any SVG body as a direct child of `body` to `display:none` to hide any spritesheets being injected, eg; `body > svg { display: none; }`

**Comment by dkevey** [comment]
> Can mega menu div be placed outside of main Vue ui div to ensure no JS conflicts? 

This needs to be tested outside of the CMS, as I've not been successful in getting it to work in CMS. Content outside of `<div id="ui"> `is not being included.

**Comment by angieraj** [comment]
@gepifanio can we test this outside the CMS?

**Comment by gepifanio** [comment]
PR: https://github.com/unimelb/Gen4/pull/45
