### ISSUE TITLE
[a11y] Gen 2 mega menu promo images and links create duplicate destinations

### ISSUE THREAD

**Issue by jaredhenderson** [unimelb/pattern-lib#1661]
## Currently

The G2 mega menu allows for promo images which also feature a text link to the same page/destination. This causes an accessibility issue because there are two differently named links pointing to the same destination.

![Screen Shot 2021-06-10 at 2.05.53 pm.png](https://images.zenhubusercontent.com/5acae0cd4b5806bc2bce3338/c6f7994a-345c-4c0c-9fcb-95c0605f1168)

## Proposed changes

There are a few alternatives:

- [x] Remove the link text
- [x] Move the link wrapper around the image to the description text
- [x] Style the description text like the other menu items with a chevron

**Comment by gepifanio** [comment]
pr: https://github.com/unimelb/pattern-lib/pull/1707
