### ISSUE TITLE
[Chore] Update Today Mega-menu alt with styling tweaks

### ISSUE THREAD

**Issue by jaredhenderson** [unimelb/pattern-lib#1670]
### Changes from Brendan homepack go-live feedback
See [Slack thread from Andrew](https://unimelb.slack.com/archives/GR6U3H248/p1624341463004800)

![Screen Shot 2021-06-22 at 4.09.52 pm.png](https://images.zenhubusercontent.com/5acae0cd4b5806bc2bce3338/f117027b-9b7b-463a-9066-62102f87e406)

### Changes to make
- [x] update secondary links to use `text-transform: uppercase`
- [x] add extra spacing between primary links - suggest +0.75rem

**Comment by gepifanio** [comment]
pr: https://github.com/unimelb/pattern-lib/pull/1671
