### ISSUE TITLE
Adding a new query string to video components

### ISSUE THREAD

**Issue by angieraj** [unimelb/pattern-lib#1696]
At the moment the videos on Study homepage https://study.unimelb.edu.au/ have an option to switch on captions. 

However we would like to have the captions turned on by default. 

We can get YouTube to show the captions by default by using the cc_load_policy parameter:
https://developers.google.com/youtube/player_parameters
https://www.youtube.com/watch?v=xd24_NnzKy4

Recent research from Andy regarding Down Syndrome showed that displaying both speakers faces and captions, substantially increased engagement.

Requirement is to add an additional query string **?cc_load_policy=1** which causes closed captions to be shown by default, even if the user has turned captions off. 

Can we please add this to all videos in pattern library

**Comment by gepifanio** [comment]
PR: https://github.com/unimelb/pattern-lib/pull/1700
