### ISSUE TITLE
[Issues] Footer and page background colour (G2 + G3)

### ISSUE THREAD

**Issue by jaredhenderson** [unimelb/pattern-lib#1710]
### Previously
In Gen 2, a navy background colour is set on the `body` so that when a page is short and the footer doesn't reach the bottom of the viewport, it blends in seamless with the bottom of the footer.

### Currently
In Gen 3, background colours are not set, so the pages default to white. On short pages, this results in the following:

![Screen Shot 2021-07-23 at 13.32.02.png](https://images.zenhubusercontent.com/5acae0cd4b5806bc2bce3338/b02e38e5-19c9-4686-9afb-646a5b5d57c9)

This makes the design feel a bit clunky and unfinished. The chevron SVGs are also missing.

**Any solution should be replicated in both G2 and G3 for consistency.**

Example G3 page:
https://cms.unimelb.edu.au/myaccount/lookup
https://students.unimelb.edu.au/sortsite-test

Example G2 page:
https://study.unimelb.edu.au/sortsite-test

### Potential fixes to be investigated
**Warning: all of these options have potential side-effects**
- Add `background-color` on `body` to match colour on bottom of footer. Result:

![Screen Shot 2021-07-23 at 13.34.20.png](https://images.zenhubusercontent.com/5acae0cd4b5806bc2bce3338/621b5afa-a91e-42c5-8f40-8e37b9a4c26b)

  - Would need to ensure page content background is still white

- Add a `min-height` to the `main` content block so pages have a minimum height; suggest `25rem`
  - this is probably not ideal, it would be better if the page itself was always 100% browser height so this wasn't necessary, but that could be challenging

- Investigate and resolve missing chevron icons

**Comment by gepifanio** [comment]
pr pattern-lib: https://github.com/unimelb/pattern-lib/pull/1712
pr gen3: https://github.com/unimelb/Gen3/pull/262
pr gen3 missing icons: https://github.com/unimelb/Gen3/pull/261
