### ISSUE TITLE
Stats and rankings component not displaying icons correctly

### ISSUE THREAD

**Issue by rock-san** [unimelb/pattern-lib#757]
Stats and rankings component not displaying svg icons correctly if the icons are the standard size of the new icons. They only fit the icons Hive initially supplied with the first concepts of the About Us page.

![screen shot 2018-06-14 at 3 22 40 pm](https://user-images.githubusercontent.com/30132691/41445230-8269bd66-708b-11e8-8624-1f44fb2badf3.png)

The icons Hive made need to be brought inline with the other icons since they are being used on other pages and aren't cohesive. But if I update the Hive icons they won't be correctly displayed.

Screenshot from: https://study.unimelb.edu.au/study-with-us/our-degrees/academic-experience

![screen shot 2018-06-15 at 11 39 26 am](https://user-images.githubusercontent.com/30132691/41446096-f4e43920-7090-11e8-9694-9659fe72b8a5.png)

**Comment by gepifanio** [comment]
As I could see on the website, the issue has been resolved.
