### ISSUE TITLE
[DESIGN] Redesign icon set

### ISSUE THREAD

**Issue by rock-san** [unimelb/pattern-lib#856]
Icons should be moved to the new style which is square, in the grid and reaches the edge of the artboard.

![screen shot 2018-08-28 at 1 33 34 pm](https://user-images.githubusercontent.com/30132691/44701585-cb920a80-aad2-11e8-8fb1-2a5e641d3d8d.png)

**Comment by jaredh-um** [comment]
Not proceeding with further Gen 2 enhancements, closing.
