### ISSUE TITLE
[DESIGN REVIEW NEEDED] two styles of link lists with title and description

### ISSUE THREAD

**Issue by rock-san** [unimelb/pattern-lib#860]
Two similar styles on homepage, need to decide on one common style

![screen shot 2018-08-31 at 2 59 34 pm](https://user-images.githubusercontent.com/30132691/44893642-65ee8a00-ad2f-11e8-980b-e0efa4c667c3.png)

and

![screen shot 2018-08-31 at 2 59 50 pm](https://user-images.githubusercontent.com/30132691/44893650-6be46b00-ad2f-11e8-9d66-70d433e925df.png)

**Comment by jaredh-um** [comment]
Will be deprecated with new homepage design.
