### ISSUE TITLE
Custom Reconciliation branding

### ISSUE THREAD

**Issue by rock-san** [unimelb/pattern-lib#861]
A few tweaks are needed in Pattern Library to accomodate custom branding for Reconciliation

# Changes needed:

## Custom carousel, the swatches can be found on Invision DSM. https://projects.invisionapp.com/dsm/university-of-melbourne/uo-m-ui-kit/folder/colors/5b3d9e50371f710011671a16 If unable to access Invision DSM, the colour order will be as follows:

- Orange Mid 2
- Teal Mid 2
- Yellow Mid 2
- Green Mid 2

## Custom background Images: (Image files are kept here https://unimelbcloud.sharepoint.com/:f:/r/teams/DigitalOnlineChannels/Shared%20Documents/Projects/Pattern%20Library/UI%20Kit/Resources/Images/backgrounds/reconciliation?csf=1&e=tCvbeT)

- For Level 3 Banner (reconciliation-header)
- Crest Divider (reconciliation1)
- For focus pathfinder (reconciliation2)

# Mockups

## Mockup 1

![reconciliation-custom-brand-sample-1](https://user-images.githubusercontent.com/30132691/46265338-d83dce80-c568-11e8-8f65-e0c0e5eef545.png)

## Mockup 2

![reconciliation-custom-brand-sample-2](https://user-images.githubusercontent.com/30132691/46265339-d96efb80-c568-11e8-9e39-b467e5bae66a.png)

**Comment by dylankelly** [comment]
![reconciliation-banner-background 2x](https://user-images.githubusercontent.com/2186721/46588621-392a5100-caeb-11e8-87a5-2681dc167585.png)
![reconciliation-banner-background](https://user-images.githubusercontent.com/2186721/46588622-39c2e780-caeb-11e8-8a72-66c8b42e1b30.png)

**Comment by dylankelly** [comment]
closed in 3.5.1
