### ISSUE TITLE
Update package.json scripts to allow usage on windows

### ISSUE THREAD

**Issue by TimMansell** [unimelb/pattern-lib#873]
At the moment some node scripts inside _package.json_ don't work on a windows environment.  This is due to:

**_&&_** failing on cmd.exe:
```code
"lint": "yarn run lint:js && yarn run lint:css"
```
Unix commands need refactoring to a npm plugin. ie, rm:
```code
"prebuild": "rm -Rf .out/docs"
```
Setting environment variables:
```code
"build:lib": "NODE_ENV=production webpack --config targets/lib/webpack.config.js"
```

Suggestion:

Use https://www.npmjs.com/package/npm-run-all to allow cross platform use.
Use https://www.npmjs.com/package/rimraf to delete files
Use https://www.npmjs.com/package/cross-env to set environment variables

**Comment by gepifanio** [comment]
@TimMansell Closing this issue as already has been resolved.
