### ISSUE TITLE
Search button text is not vertically centred

### ISSUE THREAD

**Issue by jaredh-um** [unimelb/pattern-lib#875]
Search button text is not being vertically centred.

## Expected behaviour
Text and icon are vertically centred
![Screen Shot 2018-11-15 at 11.58.29 am.png](https://images.zenhubusercontent.com/5acae0cd4b5806bc2bce3338/243d46c6-3b4d-4504-ad7c-21ecacec0f47)

## Current behaviour
Text and icon are aligned to top
![Screen Shot 2018-11-15 at 11.52.16 am.png](https://images.zenhubusercontent.com/5acae0cd4b5806bc2bce3338/0a4623e3-3f2c-48e2-b131-9bac115d6e6f)

## Steps to reproduce
[Live in Pattern Library](https://pattern-lib-unimelb.netlify.com/?selectedKind=Forms&selectedStory=Inline%20search%20form%20%28min%29&full=0&addons=1&stories=1&panelRight=0&addonPanel=REACT_STORYBOOK%2Freadme%2Fpanel)

### Affected browsers
I haven't tested extensively but there's no align-items value set so I don't expect it to be working anywhere.
- [X] Chrome
- [X] Firefox
- [ ] Edge
- [ ] IE 11
- [ ] Safari 8+
- [ ] iOS 8.4+
- [ ] Android 4.4+

## Possible solution
(I think) `align-items: center` needs to be added to the selectors `button.form--inline__button, button.section .form--inline__button`

**Comment by jaredh-um** [comment]
Fix also proposed in [FFAM issue 435](https://github.com/unimelb/ffam-prototype/issues/435).

**Comment by gepifanio** [comment]
PR: https://github.com/unimelb/pattern-lib/pull/1173
