### ISSUE TITLE
Add Accessibility plugin to Storybook 

### ISSUE THREAD

**Issue by meligatt** [unimelb/pattern-lib#880]
This plugin added to storybook UI can be useful to check accessibility issues at the component level.
Check here for more information
`https://www.npmjs.com/package/@storybook/addon-a11y`

**Comment by gepifanio** [comment]
Tried to add `addon-a11y` and didn't work properly, seems that only works with the newest version of the storybook, so in the meanwhile, I will add the `vue-axe`.

https://github.com/vue-a11y/vue-axe
