### ISSUE TITLE
[Tech debt] Add Unit test coverage to Pattern-library components

### ISSUE THREAD

**Issue by meligatt** [unimelb/pattern-lib#889]
Problem: 
really low test coverage  found on pattern library codebase.

## Expected behaviour
Every component should have a unit test.

## Current behaviour
- just `page/breadcrumbs` and `page/footer` have tests.
- the rest of components have no snapshot test nor unit test.

**Comment by TimMansell** [comment]
Have implemented snapshot test for all components
