### ISSUE TITLE
Check if the CSS overrides are still required in CMS Matrix

### ISSUE THREAD

**Issue by gepifanio** [unimelb/pattern-lib#903]
## Problem

When we originally put the new design into Matrix, there were a number of CSS fixes that were included in Matrix itself to override or fix issues. Check if those overrides are still required, now that the Pattern Library is more mature.

## Overrides in Matrix

```
/* 
Template Name: uom-mce.css
Atomisk DDS Version: 0.0.4
Author: External Relations Digital Team - Based on UoM Design Template
Updated: 04/12/2017 DK
*/

/* helpers for CMS */
.text-small {font-size: 90%;}
.text-smaller {font-size: 80%;}

pre {line-height: 1; background-color: #eee; padding: 20px;}
/* remove padding at top or bottom of content blocks because sometimes there is too much */
.short {padding-top: 1.5rem; padding-bottom: 1.5rem;}
.nopad {padding-top: 0rem; padding-bottom: 0rem; margin-top: 0rem; margin-bottom: 0rem;}
.nopadtop {padding-top: 0rem; margin-top: 0rem;}
.nopadbottom {padding-bottom: 0rem; margin-bottom: 0rem;}

/* grey lead text for use in section divider headings */
.lead-grey {font-size: 1.25rem; color: #d8d8d8; font-family: Source Sans Pro,Gill Sans,Trebuchet MS,Arial,sans-serif; font-weight: 600;}

/* Fixes IE issue with backgrounds. Will be added to future rebrand versions */
main { display: block; } 

/* Fixed IE issue with cards */
.card--link p.card__header {
  max-width: 100%;
}
```

**Comment by gepifanio** [comment]
Hey @dkevey,  Could you validate if this still needed to be overridden by the CMS? if yes, let us know to fix in the pattern-lib and make sure in the future we do not have overrides in the CMS side.

**Comment by TimMansell** [comment]
Hi @dkevey, any update on this.  Would be good to remove or migrate over to pattern library.

**Comment by dkevey** [comment]
@gepifanio it's a bit bigger now https://matrix-cms.unimelb.edu.au/__data/assets/css_file_folder/0031/164956/mce-extras.css?v=0.0.48 not sure that it's worth worrying about if we're moving to Gen 4.

**Comment by jaredh-um** [comment]
Let's not worry about these for now; hopefully these issues can be natively addressed by Gen 4 and we can remove the overrides at some future point.
