### ISSUE TITLE
[pattern-lib: FFAM] Component - Filters

### ISSUE THREAD

**Issue by meligatt** [unimelb/pattern-lib#910]
Trello card: https://trello.com/c/r4jfYcX7

**Comment by gepifanio** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Component - Filters](https://trello.com/c/r4jfYcX7/1-component-filters)

**Comment by meligatt** [comment]
I will close this issue to not create duplicate tickets about the same thing. this ticket can be found in FFAM board along with a full tech spect (version 1) https://app.zenhub.com/workspaces/ffam-prototype-5c615588801d5a103031639c/issues/unimelb/ffam-prototype/9
