### ISSUE TITLE
Automate Pattern-lib CLI to add automatic new components to the index.js targets (Vue and Matrix CMS)

### ISSUE THREAD

**Issue by gepifanio** [unimelb/pattern-lib#933]
## Expected behavior

All new components should be automatically added to both targets (Vue and Matrix CMS)

## Current behavior

You need to add manually.

**Comment by jaredhenderson** [comment]
Over two years old and hasn't been actioned; not sure it is a good move as we already include every single component and our payload is 600KB+.

**Comment by jaredhenderson** [comment]
Over two years old and hasn't been actioned; not sure it is a good move as we already include every single component and our payload is 600KB+.
